package compman.compsrv.model.dto.brackets;

public enum BracketType {
    CHAVE_DE_3, SINGLE_ELIMINATION, SINGLE_ELIMINATION_3D_PLACE, SINGLE_ELIMINATION_ALL_PLACES, DOUBLE_ELIMINATION, GROUP, MULTIPLE_GROUPS, JUDO_SYSTEM
}
