package compman.compsrv.model.commands;

public enum CommandType {
    CHECK_CATEGORY_OBSOLETE,
    CHANGE_COMPETITOR_CATEGORY_COMMAND,
    SAVE_SCHEDULE_COMMAND,
    SAVE_ABSOLUTE_CATEGORY_COMMAND,
    GENERATE_SCHEDULE_COMMAND,
    GENERATE_BRACKETS_COMMAND,
    UPDATE_CATEGORY_FIGHTS_COMMAND,
    DROP_SCHEDULE_COMMAND,
    DROP_ALL_BRACKETS_COMMAND,
    DROP_CATEGORY_BRACKETS_COMMAND,
    SAVE_BRACKETS_COMMAND,
    START_COMPETITION_COMMAND,
    STOP_COMPETITION_COMMAND,
    UPDATE_COMPETITION_PROPERTIES_COMMAND,
    CREATE_COMPETITION_COMMAND,
    PUBLISH_COMPETITION_COMMAND,
    UNPUBLISH_COMPETITION_COMMAND,
    DELETE_COMPETITION_COMMAND,
    ADD_CATEGORY_COMMAND,
    DELETE_CATEGORY_COMMAND,
    FIGHTS_EDITOR_APPLY_CHANGE,
    ADD_REGISTRATION_PERIOD_COMMAND,
    CREATE_REGISTRATION_GROUP_COMMAND,
    DELETE_REGISTRATION_GROUP_COMMAND,
    DELETE_REGISTRATION_PERIOD_COMMAND,
    ASSIGN_REGISTRATION_GROUP_CATEGORIES_COMMAND,
    UPDATE_REGISTRATION_INFO_COMMAND,

    //dummy command
    DUMMY_COMMAND,
    INTERNAL_SEND_PROCESSING_INFO_COMMAND,

    //mat state commands
    INIT_MAT_STATE_COMMAND,
    DELETE_MAT_STATE_COMMAND,
    INIT_PERIOD_COMMAND,
    DELETE_PERIOD_COMMAND,
    CREATE_DASHBOARD_COMMAND,
    DELETE_DASHBOARD_COMMAND,
    DASHBOARD_FIGHT_ORDER_CHANGE_COMMAND,
    ADD_UNDISPATCHED_MAT_COMMAND,
    CHECK_DASHBOARD_OBSOLETE,

    CHECK_MAT_OBSOLETE,
    SET_CATEGORY_BRACKETS_COMMAND,

    PUBLISH_EVENTS_COMMAND,

    ADD_COMPETITOR_COMMAND,
    CREATE_FAKE_COMPETITORS_COMMAND,
    UPDATE_COMPETITOR_COMMAND,
    REMOVE_COMPETITOR_COMMAND
}
