version: '3.9'
services:
  client_ui:
    image: client-ui:latest
    ports:
      - "80:80"
    environment:
      TEST: true

    networks:
      compsrv_backend:

networks:
  compsrv_backend:
    external: true