version: '3.8'
services:

  query_service:
    image: query-processor:latest
    environment:
      - KAFKA_BROKERS=broker:29092
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    networks:
      compsrv_backend:
    deploy:
        restart_policy:
          condition: on-failure
    depends_on:
      - cassandra
    ports:
      - "9000:8080"


  gateway_service:
    image: gateway-service:latest
    environment:
      - KAFKA_BROKERS=broker:29092
    networks:
      compsrv_backend:
    depends_on:
      - broker
    ports:
      - "8080:8080"


  saga_processor:
    image: saga-processor:latest
    environment:
      - DATABASE_PATH=/app/app-db/saga-processor
      - KAFKA_BROKERS=broker:29092
    volumes:
      - saga_processor_db:/app/app-db/saga-processor
    networks:
      compsrv_backend:
    depends_on:
      - broker


  cassandra:
    image: cassandra:latest
    container_name: compsrv-cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./app-data/cassandra:/var/lib/cassandra
      - ./app-data/logs:/var/log/cassandra
    networks:
      compsrv_backend:
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations:
          memory: 1GB

  broker:
    image: confluentinc/cp-kafka:6.2.1
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose-backend.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      compsrv_backend:

volumes:
  saga_processor_db:
  query_processor_db:

networks:
  compsrv_backend: