/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "competitionservice"
include(":compservice-annotation-processor")
include(":competition-serv-model")
include(":compservice-annotations")
include(":command-processor")
include(":command-processor:commons")
include(":query-processor")
include(":kafka-common")
include(":kafka-common:kafka-common-test")
include(":actor-system")
include(":gateway-service")
