/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "competitionservice"
include(":compservice-annotation-processor")
include(":competition-serv-model")
include(":compservice-annotations")
include(":saga-processor")
