package compman.compsrv.logic.fight

import compservice.model.protobuf.model.FightResultOption

object FightResultOptionConstants {
  val WIN_POINTS: FightResultOption = FightResultOption()
    .withId("_default_win_points")
    .withWinnerPoints(3)
    .withWinnerAdditionalPoints(1)
    .withDescription("Win by points")
    .withShortName("Win points")
  val WIN_SUBMISSION: FightResultOption = FightResultOption()
    .withId("_default_win_submission")
    .withWinnerPoints(3)
    .withWinnerAdditionalPoints(2)
    .withDescription("Win by submission")
    .withShortName("Win submission")
  val WIN_DECISION: FightResultOption = FightResultOption()
    .withId("_default_win_decision")
    .withWinnerPoints(3)
    .withWinnerAdditionalPoints(0)
    .withDescription("Win by decision")
    .withShortName("Win decision")
  val OPPONENT_DQ: FightResultOption = FightResultOption()
    .withId("_default_opponent_dq")
    .withWinnerPoints(3)
    .withWinnerAdditionalPoints(0)
    .withDescription("Win because opponent was disqualified")
    .withShortName("Win opponent DQ")
  val WALKOVER: FightResultOption = FightResultOption()
    .withId("_default_walkover")
    .withWinnerPoints(3)
    .withWinnerAdditionalPoints(0)
    .withDescription("Win" +
      " because opponent didn't" +
      " show up or got injured, or some other reason.")
    .withShortName("Win walkover")
  val BOTH_DQ: FightResultOption = FightResultOption()
    .withId("_default_both_dq")
    .withWinnerPoints(0)
    .withWinnerAdditionalPoints(0)
    .withLoserPoints(0)
    .withLoserAdditionalPoints(0)
    .withDescription("Both competitors were disqualified")
    .withDraw(true)
    .withShortName("Both DQ")
  val DRAW: FightResultOption = FightResultOption()
    .withId("_default_draw")
    .withWinnerPoints(1)
    .withWinnerAdditionalPoints(0)
    .withLoserPoints(1)
    .withLoserAdditionalPoints(0)
    .withDraw(true)
    .withDescription("Draw")
    .withShortName("Draw")

  val values: List[FightResultOption] = List(WIN_POINTS, WIN_SUBMISSION, WIN_DECISION, OPPONENT_DQ, WALKOVER, BOTH_DQ, DRAW)

}
