#Profiles:
#el-zookeeper: manual leader election with zookeeper
#el-curator: leader election with curator's recipe
#dev - developer's profile (for test instances of zookeeper and kafka)

spring:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: compman
#      password: compManagerPassword
#      database: compservice
#      authentication-database: admin
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:mysql://localhost:3306/competition?serverTimezone=UTC
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet.context-path: /competitions
  port: 8082

communication:
  frontend-callback-url: http://localhost:8080/
  account-service: http://localhost:8089/
  query-service: http://localhost:9000/


cluster:
  zookeeper:
    connection-string: 127.0.0.1:65314
    connect-timeout: 10000
    session-timeout: 20000
  enable-cluster: true
  advertised-port: 60390

kafka:
  bootstrap-servers: 127.0.0.1:65332
  stream-properties:
    application.id: competition_service
    bootstrap.servers: ${kafka.bootstrap-servers}
    processing.guarantee: at_least_once
    cache.max.bytes.buffering: 0
    num.stream.threads: ${kafka.default-topic-options.partitions}
  consumer:
    properties:
      bootstrap.servers: ${kafka.bootstrap-servers}
      group.id: compserv_consumer
      enable.auto.commit: true
      value.deserializer: compman.compsrv.kafka.serde.CommandDeserializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
    - name: competition_commands
  producer:
    topic:
      name: competition_events
    properties:
     bootstrap.servers: ${kafka.bootstrap-servers}
     acks: "all"
     retries: 0
     batch.size: 16384
     linger.ms: 1
     buffer.memory: 33554432
     key.serializer: org.apache.kafka.common.serialization.StringSerializer
     value.serializer: org.apache.kafka.common.serialization.StringSerializer
  default-topic-options:
    partitions: 4
    replication-factor: 1


management:
  endpoints.web.exposure.include: '*'
  server:
    port: 9001
    address: 127.0.0.1