security:
  oauth2:
    client:
      clientId: competition-service
      clientSecret: test
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current


spring:
  application:
    name: competition-service
  kafka:
    bootstrap-servers:



server:
  servlet.context-path: /competitions
  port: 8082

mongodb:
  host: localhost
  username: compman
  password: compManagerPassword
  database: compservice
  port: 27017
  admindb: admin
  auth: false

communication:
  frontend-callback-url: http://localhost:8080/
  account-service: http://localhost:8089/


cluster:
  zookeeper:
    connection-string: 127.0.0.1:65314
    connect-timeout: 10000
    session-timeout: 20000
  enable-cluster: true
  advertised-host: "localhost"
  advertised-port: ${server.port}

kafka:
  bootstrap-servers: 127.0.0.1:65332
  stream-properties:
    application.id: competition_service
    bootstrap.servers: ${kafka.bootstrap-servers}
    processing.guarantee: at_least_once
    cache.max.bytes.buffering: 0
    num.stream.threads: ${kafka.default-topic-options.partitions}
  consumer:
    properties:
      bootstrap.servers: ${kafka.bootstrap-servers}
      group.id: compserv_consumer
      enable.auto.commit: true
      value.deserializer: compman.compsrv.kafka.serde.CommandDeserializer
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
    - name: competition_commands
  producer:
    topic:
      name: competition_events
    properties:
     bootstrap.servers: ${kafka.bootstrap-servers}
     acks: "all"
     retries: 0
     batch.size: 16384
     linger.ms: 1
     buffer.memory: 33554432
     key.serializer: org.apache.kafka.common.serialization.StringSerializer
     value.serializer: org.apache.kafka.common.serialization.StringSerializer
  default-topic-options:
    partitions: 4
    replication-factor: 1


management:
  endpoints.web.exposure.include: '*'
  server:
    port: 9001
    address: 127.0.0.1